### ISSUE TITLE
Implement RESTler fuzzing with an API that requires authentication

### ISSUE THREAD

**Issue by sharmig571** [microsoft/rest-api-fuzz-testing#140]
I am having a .NET core application and we have several microservices. The swagger APIs are authenticated with tokens. I wanted to implement fuzzing using RESTler but I am unable to figure out how to integrate RESTler with an API that requires authentication. Can someone provide a working example please.

**Comment by stishkin** [comment]
Hi @sharmig571 

Documentation on how to authenticate using tokens:

https://github.com/microsoft/rest-api-fuzz-testing/blob/aa3acaa18f99f1f41ac386523da1353334418879/docs/schema/authentication.md

TxtToken is the section that you are looking for.


If you want to see a sample config - you can see any "Raft on Raft" samples, and instead of MSAL use TxtToken for authentication.


When you add tokens to your keyvault, you will need to run `raft.py service restart`.
Restart will not be required in next release (but right now it is needed for keyvault values to be updated)

**Comment by stishkin** [comment]
I'll write up step by step how to setup token authentication

**Comment by stishkin** [comment]
@sharmig571 

PR with step by step explanation how to use a token: 

https://github.com/microsoft/rest-api-fuzz-testing/pull/143/files?short_path=37e87e8#diff-37e87e81785ccfed2444459553c1037f398eafb450321cbcf0fc08b16e933e98
