### ISSUE TITLE
Authentication on API specification directory

### ISSUE THREAD

**Issue by LinaKulakova** [microsoft/rest-api-fuzz-testing#224]
Hey!
I've read the documentation and issues around here and although there are tons of info regarding authentication, I don't know whether it is possible to use an API that has its specification under authentication. 
I've set up a project according to the samples but in my case, the API is not under authentication but API's swagger file/specification is. 
I would need a way to pass the secrets to access the swagger definition. 

Thanks

**Comment by stishkin** [comment]
At this point we don't have support for situation when swagger spec is behind authentication. 

As a work around you can download the swagger specification, and pass file path to the specification in your configuration instead of URL. 
See this for example on how to do that:

[https://github.com/microsoft/rest-api-fuzz-testing/issues/190#issuecomment-828548874](https://github.com/microsoft/rest-api-fuzz-testing/issues/190#issuecomment-828548874)

**Comment by LinaKulakova** [comment]
Thanks for the answer!
