### ISSUE TITLE
azure.servicebus method names changed

### ISSUE THREAD

**Issue by hookjr** [microsoft/rest-api-fuzz-testing#67]
For ZAP tool API scan is failing to import TopicClient and Message from azure.servicebus. These have been replaced with ServiceBusClient and ServiceBusMessage respectively. Affects scan.py

**Comment by hookjr** [comment]
Looks like this version also requires a specific topic, is there an environment variable for fetching the Topic Name?

**Comment by stishkin** [comment]
Yes you are right. I have a fix in the following branch. 

https://github.com/microsoft/rest-api-fuzz-testing/tree/schema-v2

Pull request that fixes the issue:

https://github.com/microsoft/rest-api-fuzz-testing/pull/62/files

We don't want to merge that branch yet into main, since it will introduce breaking changes to existing users. 

If you don't have any job configs that schema change would break - you are welcome to try out the schema-v2 branch, and ZAP works there ok

**Comment by hookjr** [comment]
Thanks for the update!
